language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - COMPOSER_FLAGS=""
        - MODE="test" # Allowed values: [test, syntax, coverage]
        - TEST_COMMAND="composer test"

php:
    - 7.2
    - 7.3

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.3
          env: DEPENDENCIES=beta
        - php: 7.2
          env: MODE="syntax" TEST_COMMAND="composer syntax"
        - php: 7.3
          env: MODE="coverage" TEST_COMMAND="composer coverage"

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
    - if [[ $MODE != "coverage" ]]; then phpenv config-rm xdebug.ini || true; fi

install:
    - travis_retry composer update --prefer-dist --no-progress --no-suggest $COMPOSER_FLAGS --ansi

script:
    - $TEST_COMMAND

after_success:
    - if [[ $MODE = "coverage" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $MODE = "coverage" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
